export const WORD_POOLS: Record<string, string[]> = {
  nouns: [
    'age', 'air', 'arc', 'arm', 'art', 'ash', 'bay', 'bit', 'box', 'bud',
    'bug', 'bus', 'cap', 'cat', 'cup', 'cut', 'day', 'den', 'dog', 'dot',
    'ear', 'egg', 'end', 'era', 'eye', 'fan', 'fur', 'gap', 'gem', 'gig',
    'gum', 'gym', 'ham', 'hat', 'hay', 'hub', 'hue', 'ice', 'ink', 'inn',
    'ivy', 'jar', 'joy', 'jug', 'kid', 'kit', 'lab', 'lap', 'law', 'leg',
    'lid', 'lip', 'log', 'lot', 'map', 'mat', 'mud', 'mug', 'net', 'oak',
    'oil', 'ore', 'pad', 'pan', 'pea', 'pen', 'pet', 'pie', 'pig', 'pin',
    'pit', 'pod', 'pub', 'ray', 'rib', 'rim', 'rod', 'row', 'rug', 'rut',
    'rye', 'sap', 'sea', 'son', 'spa', 'sum', 'sun', 'tab', 'tar', 'tax',
    'tea', 'tie', 'toe', 'ton', 'toy', 'tub', 'urn', 'van', 'vow', 'wax',
    'web', 'zoo', 'atom', 'axis', 'ball', 'band', 'bank', 'barn', 'bath',
    'beam', 'bean', 'bear', 'beef', 'beer', 'bell', 'belt', 'bike', 'bird',
    'boat', 'bolt', 'bond', 'bone', 'book', 'boot', 'boss', 'bowl', 'byte',
    'cage', 'cake', 'camp', 'cane', 'cape', 'card', 'cart', 'cave', 'cell',
    'chip', 'city', 'clan', 'clay', 'club', 'coal', 'coat', 'coil', 'coin',
    'comb', 'cone', 'copy', 'cord', 'core', 'corn', 'cove', 'crew', 'crop',
    'cube', 'curl', 'dart', 'data', 'date', 'dawn', 'deal', 'deck', 'deer',
    'desk', 'disc', 'dish', 'disk', 'dome', 'door', 'dove', 'drum', 'dune',
    'dust', 'edge', 'face', 'fact', 'fame', 'farm', 'fate', 'feat', 'file',
    'film', 'fire', 'fish', 'flag', 'flaw', 'foam', 'fold', 'font', 'food',
    'foot', 'fork', 'fort', 'fuel', 'fume', 'fuse', 'gate', 'gear', 'gene',
    'gift', 'girl', 'goal', 'goat', 'gold', 'golf', 'grab', 'gram', 'grid',
    'gulf', 'gust', 'hail', 'hair', 'hall', 'hand', 'harm', 'haze', 'heap',
    'heel', 'helm', 'herb', 'hero', 'hill', 'hive', 'hole', 'hook', 'horn',
    'hose', 'host', 'hour', 'hull', 'hymn', 'icon', 'idea', 'inch', 'iris',
    'iron', 'isle', 'item', 'jade', 'jazz', 'joke', 'jury', 'kelp', 'king',
    'knee', 'knob', 'knot', 'lace', 'lake', 'lamp', 'land', 'lane', 'leaf',
    'leak', 'lens', 'lime', 'line', 'link', 'lion', 'list', 'load', 'loan',
    'lock', 'loft', 'loom', 'loop', 'lord', 'lore', 'loss', 'luck', 'lung',
    'lure', 'mail', 'mane', 'mark', 'mast', 'maze', 'meal', 'meat', 'mesh',
    'mile', 'milk', 'mill', 'mine', 'mint', 'mist', 'moon', 'moss', 'mule',
    'myth', 'nail', 'name', 'neck', 'nest', 'news', 'nick', 'node', 'noon',
    'norm', 'nose', 'note', 'oboe', 'oven', 'pace', 'pack', 'page', 'pain',
    'pair', 'palm', 'park', 'path', 'peak', 'pile', 'pine', 'pipe', 'plot',
    'plum', 'poem', 'poet', 'pole', 'poll', 'pond', 'pool', 'pore', 'port',
    'prey', 'prop', 'pump', 'rack', 'rain', 'rake', 'ramp', 'rank', 'reef',
    'rent', 'rice', 'ring', 'riot', 'risk', 'road', 'robe', 'rock', 'role',
    'roof', 'room', 'root', 'rope', 'rose', 'ruby', 'ruin', 'rule', 'rust',
    'sage', 'sail', 'salt', 'sand', 'seal', 'seed', 'self', 'shed', 'ship',
    'shoe', 'shop', 'shot', 'side', 'sign', 'silk', 'silo', 'slab', 'slot',
    'slug', 'snap', 'snow', 'soap', 'sock', 'soil', 'sole', 'song', 'soot',
    'soul', 'spin', 'spot', 'spur', 'star', 'stem', 'step', 'stew', 'stub',
    'suit', 'swan', 'tail', 'tale', 'tank', 'tape', 'task', 'tear', 'tent',
    'term', 'text', 'tide', 'tier', 'tile', 'time', 'tire', 'toad', 'toll',
    'tomb', 'tone', 'tool', 'tour', 'town', 'tram', 'trap', 'trek', 'trip',
    'trot', 'tube', 'tune', 'turf', 'twin', 'type', 'unit', 'user', 'veil',
    'vein', 'vest', 'vine', 'void', 'volt', 'wade', 'wage', 'wall', 'warp',
    'wave', 'weed', 'week', 'well', 'west', 'wig', 'wind', 'wine', 'wing',
    'wire', 'wolf', 'wood', 'word', 'worm', 'wrap', 'yard', 'yarn', 'year',
    'yell', 'zone', 'abbey', 'agent', 'alarm', 'album', 'alley', 'alloy',
    'angel', 'angle', 'ankle', 'annex', 'anvil', 'apple', 'arbor', 'arena',
    'array', 'attic', 'audio', 'audit', 'badge', 'basis', 'batch', 'beach',
    'beech', 'berry', 'birch', 'blade', 'block', 'blood', 'bloom', 'board',
    'bonus', 'braid', 'brain', 'brake', 'brand', 'bread', 'brick', 'bride',
    'brine', 'brink', 'brook', 'broom', 'brush', 'burst', 'candy', 'cargo',
    'cedar', 'chain', 'chair', 'chalk', 'charm', 'chest', 'child', 'choir',
    'chord', 'claim', 'class', 'clerk', 'cliff', 'clone', 'cloth', 'cloud',
    'coach', 'coast', 'comet', 'comma', 'coral', 'court', 'craft', 'crane',
    'creed', 'creek', 'crest', 'crime', 'crowd', 'crown', 'crush', 'curve',
    'cycle', 'daisy', 'debut', 'depot', 'depth', 'derby', 'digit', 'dingo',
    'disco', 'ditch', 'doubt', 'dough', 'draft', 'drain', 'drama', 'drawl',
    'dread', 'dream', 'dress', 'drift', 'dwarf', 'eagle', 'earth', 'eight',
    'elite', 'ember', 'emoji', 'entry', 'error', 'essay', 'event', 'fable',
    'facet', 'faith', 'fault', 'feast', 'fence', 'fever', 'fiber', 'field',
    'fifth', 'fight', 'flame', 'flank', 'flask', 'flesh', 'flock', 'flood',
    'floor', 'flora', 'flour', 'flute', 'force', 'forge', 'found', 'frame',
    'fraud', 'front', 'frost', 'fruit', 'fungi', 'gauge', 'ghost', 'gland',
    'glass', 'gloom', 'glory', 'gloss', 'grace', 'grade', 'grain', 'grant',
    'graph', 'grasp', 'grass', 'grave', 'grief', 'groom', 'group', 'grove',
    'guard', 'guild', 'guilt', 'guise', 'gusto', 'habit', 'hatch', 'haven',
    'hazel', 'heart', 'hedge', 'hinge', 'honey', 'honor', 'horse', 'hotel',
    'house', 'human', 'hyena', 'image', 'index', 'jewel', 'juice', 'karma',
    'kayak', 'laser', 'layer', 'lease', 'lemon', 'level', 'light', 'limit',
    'linen', 'logic', 'lunar', 'magic', 'manor', 'march', 'mayor', 'medal',
    'media', 'metal', 'micro', 'mimic', 'minus', 'model', 'month', 'moral',
    'mount', 'mouse', 'mouth', 'music', 'nerve', 'night', 'noble', 'noise',
    'north', 'novel', 'nurse', 'nymph', 'ocean', 'order', 'oxide', 'ozone',
    'paint', 'panel', 'paper', 'patch', 'peace', 'pearl', 'pedal', 'penny',
    'perch', 'phase', 'phone', 'photo', 'piano', 'pinch', 'pixel', 'pizza',
    'place', 'plaid', 'plane', 'plant', 'plaza', 'plume', 'point', 'poker',
    'poppy', 'power', 'price', 'pride', 'print', 'prize', 'probe', 'prose',
    'psalm', 'pulse', 'punch', 'pupil', 'quartz', 'queen', 'quota', 'radio',
    'rally', 'ranch', 'range', 'ratio', 'realm', 'resin', 'ridge', 'rival',
    'river', 'robot', 'rouge', 'route', 'rugby', 'ruler', 'rupee', 'salad',
    'satin', 'sauce', 'scale', 'scene', 'scent', 'scout', 'seam', 'sense',
    'seven', 'shade', 'shaft', 'shame', 'shape', 'shark', 'sheen', 'sheep',
    'shelf', 'shell', 'shirt', 'shore', 'sight', 'sixth', 'sixty', 'skull',
    'slate', 'slope', 'snack', 'snake', 'south', 'space', 'spawn', 'speed',
    'spice', 'spike', 'spine', 'spite', 'spoke', 'spoon', 'sport', 'squad',
    'stack', 'stage', 'stain', 'stamp', 'stand', 'stark', 'start', 'state',
    'stave', 'steep', 'stick', 'stock', 'stone', 'storm', 'story', 'stove',
    'straw', 'strip', 'strut', 'study', 'stuff', 'stump', 'style', 'sugar',
    'suite', 'swamp', 'sword', 'syrup', 'table', 'taste', 'taunt', 'tempo',
    'thorn', 'three', 'thumb', 'thyme', 'tiger', 'timer', 'title', 'today',
    'token', 'topic', 'torch', 'total', 'touch', 'towel', 'tower', 'toxic',
    'trail', 'train', 'trait', 'tramp', 'trash', 'trend', 'trial', 'trick',
    'trout', 'truce', 'trunk', 'truth', 'tulip', 'tumor', 'tuner', 'twirl',
    'twist', 'upper', 'upset', 'usage', 'value', 'valve', 'vapor', 'vault',
    'video', 'virus', 'visor', 'vista', 'voice', 'voter', 'vowel', 'waist',
    'waste', 'water', 'wedge', 'wheat', 'wheel', 'width', 'witch', 'woman',
    'world', 'wound', 'wrath', 'wrist', 'yacht', 'youth', 'zebra', 'zeal',
    'accent', 'agency', 'agenda', 'anchor', 'avenue', 'bakery', 'ballet',
    'banana', 'barrel', 'battle', 'beacon', 'border', 'bottle', 'bottom',
    'bounce', 'branch', 'bridge', 'bronze', 'bucket', 'budget', 'buffer',
    'button', 'cactus', 'camera', 'candle', 'canvas', 'castle', 'cattle',
    'center', 'cherry', 'circle', 'client', 'cobalt', 'coffee', 'column',
    'combat', 'copper', 'corner', 'cotton', 'course', 'credit', 'crisis',
    'custom', 'danger', 'desert', 'detail', 'dinner', 'domain', 'double',
    'driver', 'effect', 'effort', 'energy', 'engine', 'escape', 'estate',
    'factor', 'family', 'farmer', 'finger', 'folder', 'footer', 'forest',
    'fossil', 'future', 'galaxy', 'garden', 'goblin', 'gravel', 'harbor',
    'hazard', 'health', 'height', 'hollow', 'hunter', 'hybrid', 'impact',
    'income', 'insect', 'island', 'jacket', 'jigsaw', 'jingle', 'jungle',
    'kernel', 'kitten', 'knight', 'ladder', 'laptop', 'launch', 'length',
    'lesson', 'letter', 'liquid', 'living', 'magnet', 'marble', 'margin',
    'market', 'matter', 'meadow', 'memory', 'mirror', 'mobile', 'module',
    'moment', 'monkey', 'mortar', 'motion', 'muffin', 'muscle', 'mutual',
    'nature', 'needle', 'noodle', 'number', 'object', 'output', 'oyster',
    'packet', 'parent', 'parrot', 'patrol', 'pencil', 'pepper', 'permit',
    'person', 'pillar', 'pillow', 'pirate', 'planet', 'plaque', 'pocket',
    'pollen', 'portal', 'potato', 'profit', 'public', 'purple', 'puzzle',
    'rabbit', 'reason', 'record', 'region', 'render', 'repair', 'report',
    'rescue', 'resort', 'result', 'ribbon', 'ritual', 'rocket', 'rubber',
    'runner', 'saddle', 'saloon', 'sample', 'school', 'screen', 'scroll',
    'season', 'second', 'sector', 'series', 'server', 'settle', 'shadow',
    'signal', 'silver', 'simple', 'single', 'sketch', 'socket', 'source',
    'splash', 'stable', 'status', 'stream', 'street', 'stress', 'string',
    'strong', 'summer', 'supply', 'symbol', 'system', 'target', 'temple',
    'tender', 'tensor', 'ticket', 'timber', 'toggle', 'tomato', 'travel',
    'trench', 'triage', 'turkey', 'vector', 'vendor', 'vertex', 'violet',
    'virtue', 'vision', 'visual', 'volume', 'warden', 'wealth', 'weapon',
    'winter', 'wisdom', 'wonder', 'wooden', 'worker', 'yellow',
  ],

  adjectives: [
    'apt', 'big', 'dim', 'dry', 'dub', 'dye', 'fat', 'few', 'fit', 'hot',
    'hug', 'ill', 'low', 'mad', 'odd', 'old', 'own', 'raw', 'red', 'rid',
    'sad', 'shy', 'sly', 'wet', 'wry', 'bold', 'calm', 'cold', 'cool',
    'crisp', 'damp', 'dark', 'dead', 'dear', 'deep', 'dual', 'dusk', 'epic',
    'fair', 'fast', 'foul', 'free', 'full', 'glad', 'good', 'gray', 'grim',
    'hard', 'high', 'huge', 'idle', 'keen', 'kind', 'last', 'late', 'lean',
    'left', 'lone', 'long', 'loud', 'mild', 'numb', 'once', 'open', 'oval',
    'pale', 'poor', 'pure', 'real', 'rich', 'ripe', 'safe', 'same', 'sick',
    'slow', 'slim', 'soft', 'sour', 'sure', 'tall', 'tame', 'thin', 'tiny',
    'true', 'ugly', 'used', 'vast', 'very', 'warm', 'weak', 'wide', 'wild',
    'wise', 'worn', 'acute', 'agile', 'amber', 'ample', 'apart', 'ardor',
    'basic', 'bland', 'blank', 'blaze', 'blind', 'blunt', 'brave', 'brief',
    'brisk', 'broad', 'brown', 'built', 'cheap', 'chief', 'civil', 'clean',
    'clear', 'close', 'crisp', 'cross', 'cruel', 'daily', 'dazed', 'dried',
    'eager', 'early', 'exact', 'extra', 'faint', 'fatal', 'final', 'first',
    'fixed', 'flaky', 'frank', 'fresh', 'front', 'fully', 'giant', 'grand',
    'great', 'green', 'gross', 'happy', 'harsh', 'heavy', 'humid', 'ideal',
    'indie', 'inner', 'ionic', 'juicy', 'large', 'later', 'least', 'light',
    'loose', 'lower', 'loyal', 'lucid', 'lying', 'major', 'minor', 'moral',
    'muddy', 'naive', 'nasty', 'needy', 'night', 'noble', 'noted', 'outer',
    'plain', 'polar', 'prior', 'proud', 'quick', 'quiet', 'rapid', 'raspy',
    'ready', 'rough', 'round', 'royal', 'rural', 'rusty', 'sadly', 'savvy',
    'seize', 'seven', 'sharp', 'short', 'sheer', 'sixth', 'sixty', 'skill',
    'sleek', 'small', 'smart', 'solar', 'solid', 'stark', 'stale', 'steep',
    'still', 'stoic', 'sweet', 'thick', 'tight', 'tired', 'total', 'tough',
    'toxic', 'ultra', 'under', 'upper', 'usual', 'valid', 'viral', 'vital',
    'young', 'active', 'actual', 'annual', 'bitter', 'bright', 'broken',
    'clever', 'common', 'decent', 'formal', 'frozen', 'gentle', 'global',
    'golden', 'honest', 'humble', 'iconic', 'linear', 'liquid', 'little',
    'longer', 'lovely', 'mighty', 'modern', 'narrow', 'native', 'nearby',
    'pretty', 'proper', 'proven', 'recent', 'remote', 'robust', 'rocky',
    'rugged', 'secure', 'silent', 'slight', 'smooth', 'static', 'steady',
    'strict', 'subtle', 'sudden', 'tender', 'unique', 'urgent', 'useful',
    'worthy', 'absent', 'afraid', 'analog', 'biased', 'candid', 'crispy',
    'curved', 'dense', 'eager', 'finite', 'fluent', 'fragile', 'hidden',
    'hollow', 'hungry', 'intact', 'joyful', 'latent', 'lively', 'mental',
    'mortal', 'mutual', 'neural', 'opaque', 'plain', 'public', 'radial',
    'random', 'rustic', 'sacred', 'scarce', 'sharp', 'sparse', 'stable',
    'stored', 'sunlit', 'surplus', 'swift', 'tense', 'thermal', 'thorough',
    'usable', 'vivid', 'wooden', 'wasted',
  ],

  verbs: [
    'ask', 'buy', 'dig', 'dip', 'fix', 'fly', 'get', 'hit', 'hop', 'hug',
    'lay', 'let', 'mix', 'pay', 'put', 'run', 'say', 'set', 'sew', 'sit',
    'ski', 'sob', 'sow', 'try', 'tug', 'win', 'aim', 'aid', 'ban', 'bid',
    'bow', 'bud', 'cap', 'dub', 'dye', 'end', 'fan', 'fit', 'hew', 'nab',
    'nap', 'nod', 'opt', 'owe', 'pat', 'rig', 'rip', 'rob', 'rub', 'tap',
    'tie', 'tow', 'wag', 'bake', 'bend', 'bite', 'blow', 'burn', 'call',
    'came', 'care', 'cast', 'clip', 'copy', 'cure', 'dare', 'deal', 'drag',
    'draw', 'drip', 'drop', 'earn', 'exit', 'face', 'fail', 'fall', 'feel',
    'fell', 'fill', 'find', 'flip', 'flow', 'fold', 'feed', 'form', 'gain',
    'gave', 'give', 'glow', 'glue', 'grab', 'grew', 'grin', 'grip', 'grow',
    'hack', 'halt', 'hang', 'heal', 'hear', 'help', 'hide', 'hire', 'hold',
    'hook', 'hope', 'hunt', 'jump', 'keep', 'knit', 'know', 'lend', 'lift',
    'like', 'link', 'live', 'load', 'lock', 'look', 'lose', 'love', 'make',
    'mark', 'meet', 'melt', 'move', 'need', 'open', 'plan', 'play', 'plot',
    'plug', 'push', 'race', 'rake', 'rang', 'read', 'reap', 'rely', 'rest',
    'ride', 'rise', 'roam', 'roar', 'roll', 'save', 'scan', 'seek', 'sell',
    'send', 'show', 'shut', 'sigh', 'sing', 'sink', 'slip', 'snap', 'sort',
    'span', 'spin', 'stay', 'stir', 'stop', 'swap', 'swim', 'sync', 'take',
    'tell', 'tend', 'test', 'turn', 'vary', 'view', 'vote', 'wade', 'walk',
    'warn', 'wash', 'wear', 'weave', 'weld', 'wish', 'work', 'wrap', 'yell',
    'yield', 'adapt', 'admit', 'adopt', 'agree', 'align', 'allow', 'amend',
    'apply', 'argue', 'arise', 'avoid', 'begin', 'blend', 'bless', 'block',
    'boost', 'bound', 'break', 'breed', 'bring', 'build', 'carry', 'catch',
    'check', 'chunk', 'claim', 'clamp', 'clean', 'clear', 'climb', 'cling',
    'close', 'cover', 'crash', 'crawl', 'cross', 'crush', 'dance', 'delve',
    'draft', 'drain', 'dream', 'drink', 'drive', 'drown', 'enter', 'equal',
    'exist', 'exert', 'fetch', 'fight', 'float', 'focus', 'forge', 'found',
    'gauge', 'glare', 'grace', 'grasp', 'greet', 'grind', 'groan', 'guard',
    'guess', 'guide', 'match', 'merge', 'occur', 'offer', 'parse', 'pause',
    'place', 'plant', 'plumb', 'plunk', 'point', 'press', 'print', 'probe',
    'prove', 'reach', 'rebel', 'reign', 'relay', 'remix', 'renew', 'reply',
    'reset', 'serve', 'shake', 'share', 'shine', 'shock', 'shout', 'shoot',
    'slice', 'slide', 'smile', 'smash', 'smell', 'smoke', 'solve', 'sound',
    'spare', 'spark', 'speak', 'spend', 'split', 'spray', 'stand', 'steal',
    'steer', 'stomp', 'store', 'study', 'surge', 'swear', 'sweat', 'sweep',
    'teach', 'think', 'throw', 'touch', 'track', 'trade', 'trust', 'unify',
    'unite', 'uplift', 'verify', 'watch', 'weigh', 'wonder', 'access',
    'affirm', 'afford', 'amend', 'appear', 'append', 'assign', 'assist',
    'assure', 'attach', 'attack', 'belong', 'cancel', 'choose', 'create',
    'defeat', 'define', 'delete', 'detect', 'donate', 'encode', 'engage',
    'ensure', 'escape', 'expand', 'expect', 'export', 'expose', 'extend',
    'filter', 'finish', 'follow', 'forget', 'gather', 'happen', 'inject',
    'insert', 'listen', 'manage', 'modify', 'notify', 'obtain', 'offset',
    'prefer', 'refine', 'reduce', 'remove', 'repair', 'return', 'reveal',
    'review', 'rotate', 'search', 'select', 'signal', 'submit', 'supply',
    'target', 'toggle', 'travel', 'update', 'uplift', 'upload', 'verify',
    'wonder', 'accept', 'deploy', 'invoke', 'launch', 'mirror', 'output',
    'render', 'rescue', 'resume', 'retain', 'reuse', 'shrink', 'stream',
    'switch', 'unlock', 'unpack', 'unzip',
  ],

  tech: [
    'api', 'app', 'bot', 'bug', 'cdn', 'cli', 'cpu', 'css', 'dns', 'dom',
    'git', 'gpu', 'gui', 'hex', 'http', 'ide', 'ios', 'ip', 'json', 'jwt',
    'lan', 'lib', 'log', 'mac', 'orm', 'os', 'png', 'png', 'ram', 'rgb',
    'sdk', 'sql', 'ssh', 'svg', 'tcp', 'tls', 'udp', 'ui', 'url', 'ux',
    'vm', 'vpn', 'xml', 'xss', 'yaml', 'zip', 'async', 'bytes', 'cache',
    'chmod', 'crypt', 'epoch', 'flush', 'index', 'input', 'mutex', 'parse',
    'proxy', 'query', 'queue', 'regex', 'scope', 'stack', 'stdin', 'stdio',
    'token', 'tuple', 'debug', 'fetch', 'build', 'deploy', 'devops', 'diff',
    'docker', 'domain', 'encode', 'fiber', 'format', 'header', 'import',
    'kernel', 'lambda', 'layout', 'ledger', 'linter', 'logger', 'mapper',
    'memory', 'module', 'native', 'network', 'nodejs', 'object', 'packet',
    'parser', 'patch', 'plugin', 'router', 'runner', 'schema', 'script',
    'server', 'socket', 'source', 'static', 'stream', 'struct', 'syntax',
    'tester', 'thread', 'tracer', 'update', 'vector', 'worker',
  ],

  loanWords: [
    'cafe', 'entre', 'genre', 'naive', 'depot', 'blitz', 'forte', 'niche',
    'motif', 'rogue', 'gaffe', 'ballet', 'bureau', 'cliche', 'facade',
    'fiasco', 'fiesta', 'gateau', 'grotto', 'jockey', 'kitsch', 'lagoon',
    'mantra', 'matcha', 'milieu', 'morale', 'mosaic', 'paella', 'patina',
    'pillar', 'pizzaz', 'placid', 'plaque', 'plasma', 'plateau', 'protege',
    'quiche', 'regime', 'renown', 'resume', 'risque', 'riviera', 'safari',
    'samba', 'savant', 'sonata', 'tango', 'torque', 'troupe', 'tundra',
    'velvet', 'venue', 'veranda', 'vibrato', 'villa', 'vista', 'vogue',
    'waltz', 'karate', 'kimono', 'origami', 'sushi', 'bonsai', 'kaizen',
    'haiku', 'emoji', 'manga', 'samurai', 'shogun', 'tsunami', 'futon',
    'rickshaw', 'wok', 'tofu', 'ramen', 'zen', 'karma', 'avatar', 'guru',
    'yoga', 'mantra', 'nirvana', 'pundit', 'shawl', 'bungalow', 'jungle',
    'loot', 'thug', 'cargo', 'hammock', 'igloo', 'kayak', 'moccasin',
    'chipmunk', 'raccoon', 'toboggan', 'moose', 'iguana', 'taco', 'salsa',
    'avocado', 'tomato', 'potato', 'vanilla', 'chocolate', 'mesa', 'patio',
    'plaza', 'ranch', 'rodeo', 'savanna', 'sierra', 'siesta', 'sombrero',
  ],
}

export const ALL_WORDS: string[] = Object.values(WORD_POOLS).flat()
